[package]
name = "sol_pr_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17"
borsh = "1.5.1"
borsh-derive = "1.5.1"
thiserror = "1.0.24"
rand = "0.8"
ahash = "0.8"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_pr_contract"